### PR TITLE
feat(exception): Custom Exception Handler

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review:
@rkenyon1969 
@clarkjefcoat 
@skhtet

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
What is the number of the corresponding PR in ozp-backend?

**Comment by mannyrivera2010** [comment]
In Reference:
Ansible Issue - #20 
Ozp-backend - https://github.com/ozone-development/ozp-backend/issues/191

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Pull request merged**
