### PR TITLE
feat(logging): Added Audit Logging for Ngnix

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review:
@tonyalletag 
@clarkjefcoat

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
Can you make the following changes?
- change "systemName" to AppsMall
- make "version" a variable instead of hardcoding to 1.0

In my tests on my vagrant vm, the "source" always comes up blank, is that expected?

**Comment by clarkjefcoat** [comment]
We'll have to do some checks in our production environment to see exactly what we need for "source".  I'll file a new ticket if necessary.  This looks good.

:+1:

**Comment by mannyrivera2010** [comment]
Can you please review @skhtet

**Comment by tonyalletag** [comment]
:+1:

**Pull request merged**
