### PR TITLE
Redis Role

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Draft PR

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
based off https://github.com/DavidWittman/ansible-redis

**Comment by mannyrivera2010** [comment]
Please Review:
@rkenyon1969 
@akonsowski 
@clarkjefcoat
@skhtet

ozp-ansible issue:
#22
ozp-backend issue:
ozone-development/ozp-backend#189

**Comment by mannyrivera2010** [comment]
I still need to fix an error with redis. 
````
fatal: [default]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"dest": "/etc/redis/6379.conf", "group": "redis", "owner": "redis", "src": "redis.conf.j2"}, "module_name": "template"}, "msg": "AnsibleUndefinedVariable: 'redis_password' is undefined"}
````

@Reviewers: Please wait till I push again

**Comment by clarkjefcoat** [comment]
:+1:  Success with Virtualbox 5.0.20, Ansible 2.1.0.0, and Vagrant 1.8.1 on Ubuntu 14.04.

**Comment by mannyrivera2010** [comment]
Running Vagrant up requires: 
````diff
diff --git a/roles/ozp_backend/vars/main.yml b/roles/ozp_backend/vars/main.yml
index c295d18..f76da0c 100644
--- a/roles/ozp_backend/vars/main.yml
+++ b/roles/ozp_backend/vars/main.yml
@@ -3,7 +3,7 @@
 # offline is set and the release tarball is available at {{ download_dir }}
 download_from: "github"
  # branch or tag name to checkout from git repo
-git_tag_or_branch_name: "master"
+git_tag_or_branch_name: "redis_cache"
 # if jenkins, choose a project name and build number
 jenkins_project: "build-backend-latest"
 # enter a build number or "lastSuccessfulBuild" to get the latest artifact
````

**Comment by mannyrivera2010** [comment]
````ssh
ansible-playbook -i hosts_vagrant -u vagrant -k ozp_deploy_backend.yml -vvvv
````

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
